<?php
function txn_add_benificiary($userid, $cno, $cname, $bno, $bname, $bbname, $bacc, $bifsc, $bbankid, $source, $type, $method, $pan, $aadhar)
{
	$err="";
	$txn_status=1;
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	$datetime=$datetime_datetime;
	$balance_retailer=show_txn_user_balance($userid);
	$balance_client=show_txn_client_balance();
	$balance_client_dummy=show_txn_client_dummy_balance();
	$balance_admin=show_txn_admin_balance($source);
	$client_otp_pending_refund=0;
	$admin_otp_pending_refund=0;
	$admin_otp_pending_refund=admin_otp_refund();
	
	$deduction_retailer=show_user_av_rate($source);
	$deduction_client=show_client_av_rate($source);
	$deduction_admin=show_admin_av_rate($source);
	$charged=$charges=0;
	
	if($balance_retailer<$deduction_retailer && $userid!=100007)
		$err="Your Balance is low for transation.";
	if($balance_client-$balance_client_dummy+$client_otp_pending_refund<$deduction_client)
		$txn_status=4;
	if($balance_admin+$admin_otp_pending_refund<$deduction_admin)
		$txn_status=4;
	if($err=="")
	{
		$brid=0;
		$amount=0;
		$duplicate_txn=check_mt_placed($userid,$brid,$datetime,$source,$type,$method,$amount);
		$duplicate_txn=0;
		if($duplicate_txn!=0)
		{
			$err="<b>Repeated Transaction</b>:: You already had performed same transaction with same amount to this beneficiary today. If you still want to continue, kindly change transaction amount.";
		}
		else
		{
			//$err="Transaction is in progress.";
			$txn_id=$order_id=$m_id=$t_id=0;
			$user_ip=show_ip();
			$ded_ret=$deduction_retailer;
			$remain_ret=$balance_retailer-$ded_ret;
			$ded_client=$deduction_client;
			$remain_client=$balance_client-$ded_client;
			$ded_admin=$deduction_admin;
			$remain_admin=$balance_admin-$ded_admin;
			
			$qry1="";			
			$qry1="INSERT INTO $bankapi_child_txn.txn_mt_parent(date_time, retailer_id, sender, sname, receiver, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, pre_bal, amount, charges, com_charged, deducted, post_bal) value('$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret')";
			$txn_id=generate_mt_client_txn_parent($qry1);
			if($txn_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("8146145674","Txn No $txn_id started on dated $datetime_datetime");
			}
			
			$qry2="";			
			$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
			$order_id=generate_mt_client_txn_child($qry2);
			if($order_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("8146145674","Order No $order_id started on dated $datetime_datetime");
			}
			
			$qry3="";			
			$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$deduction_admin', '$charges', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
			$m_id=generate_mt_admin_txn($qry3);
			
			//update_mid_for_client
			$qry4="";
			$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
			mysql_query($qry4);
			
			//deduct_amount_for_retailer
			$qry5="";
			$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
			mysql_query($qry5);
			include_once('zf-WalletDistributed.php');
			update_user_balance($userid);
			
			//deduct_amount_for_client
			$qry6="";
			$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
			mysql_query($qry6);
			
			if($source==1)
			{
				//deduct_amount_for_admin
				$qry7="";
				$qry7="INSERT INTO $bankapi_parent_wallet.rt_eko(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
				mysql_query($qry7);
			}
			if($source==3)
			{
				//deduct_amount_for_admin
				$qry7="";
				$qry7="INSERT INTO $bankapi_parent_wallet.rt_acharya(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
				mysql_query($qry7);
			}
			if($txn_status==1 || $txn_status==3)
			{
				if($source==1)
				{
					include_once('zf-TxnSource1DmtApi.php');
					$resulted_data=add_beneficiary_with_verify($cno,$bacc,$bifsc,$bbankid);
					
					$resulted_response=$resulted_data[0];//response
					$resulted_benefid=$resulted_data[1];//benef
					$resulted_tid=$resulted_data[2];//tid
					$err=$resulted_data[3];//msg,rti,rsi,st
					if($err[2]==-1 && ($err[1]==61 || $err[1]==345))
					{
						$txn_status=2;//success
					}
					else if($err[2]==1 && $err[1]==-1)
					{
						$txn_status=-4;////failed and refund by our otp
					}
					$txn_status=3;//response awaited
					$response_message="";
					$response_message=$err[0];
					
					//update_benefid_tid_for_client_child
					$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='$resulted_benefid', tid='$resulted_tid', order_status='$txn_status' where order_id='$order_id';";
					mysql_query($qry8);
					
					//update_benefid_for_client_parent
					$qry9="update $bankapi_child_txn.txn_mt_parent set receiver_id='$resulted_benefid' where txn_id='$txn_id';";
					mysql_query($qry9);
					
					//update_benefid_tid_for_admin
					$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response', receiver_id='$resulted_benefid', tid='$resulted_tid', mmt_status='$txn_status', response_message='$response_message' where mmt_id='$m_id';";
					mysql_query($qry10);
					
					//level wise margin for client
					
					$qry11="insert into $bankapi_child_txn.txn_mt_child_margin(order_id, txn_id, lvl_1_id, lvl_1_chg, lvl_12_id, lvl_12_chg, lcl_12_chgd) value ('$order_id', '$txn_id', '100001', '3', '$userid', '$ded_ret', '$ded_ret')";
					mysql_query($qry11);
					
					//margin for admin
					
					$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$deduction_retailer', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
					mysql_query($qry12);
				}
				else if($source==3)
				{
					include_once('zf-TxnSource3DmtApi.php');
					$resulted_data=add_beneficiary_with_verify2($cno,$cname,$bacc,$bifsc,$pan,$aadhar,$m_id);
					$resulted_response=$resulted_data[6];
					$ASTransCode=$resulted_data[3];
					$ReferenceNumber=$resulted_data[4];
					$Status=$resulted_data[1];
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					if($resulted_data[5]!='' && $resulted_data[1]=='SUCCESS')
					{
						$txn_status=2;
						//update_benefid_tid_for_client_child
						$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';";
						mysql_query($qry8);
						
						//update_benefid_for_client_parent
						$qry9="update $bankapi_child_txn.txn_mt_parent set receiver_id='0' where txn_id='$txn_id';";
						mysql_query($qry9);
						
						//update_benefid_tid_for_admin
						$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response', receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', mmt_status='$txn_status', response_message='$Status' where mmt_id='$m_id';";
						mysql_query($qry10);
						
						//level wise margin for client
						
						$qry11="insert into $bankapi_child_txn.txn_mt_child_margin(order_id, txn_id, lvl_1_id, lvl_1_chg, lvl_12_id, lvl_12_chg, lcl_12_chgd) value ('$order_id', '$txn_id', '100001', '3', '$userid', '$ded_ret', '$ded_ret')";
						mysql_query($qry11);
						
						//margin for admin
						
						$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$deduction_retailer', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
						mysql_query($qry12);
					}
					else if($resulted_data[5]=='' && $resulted_data[1]=='FAILED')
					{	//update_benefid_tid_for_admin
						$txn_status=-4;
						
						$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';";
						mysql_query($qry8);
						
						$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response', receiver_id='0', tid='$ASTransCode', bank_ref_no='$ReferenceNumber', mmt_status='$txn_status', response_message='$Status' where mmt_id='$m_id';";
						mysql_query($qry10);
					}
					else
					{	//update_benefid_tid_for_admin
						$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response' where mmt_id='$m_id';";
						mysql_query($qry10);
					}
					return $resulted_data;
				}
			}
		}
	}
	return $err;//$err;
}
function txn_add_benificiary_verfied($userid, $cno, $cname, $bno, $bname, $bbname, $bacc, $bifsc, $bbankid, $source, $type, $method, $pan, $aadhar)
{
	$err="";
	$txn_status=1;
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	$datetime=$datetime_datetime;
	$balance_retailer=show_txn_user_balance($userid);
	$balance_client=show_txn_client_balance();
	$balance_client_dummy=show_txn_client_dummy_balance();
	$balance_admin=show_txn_admin_balance($source);
	$client_otp_pending_refund=0;
	$admin_otp_pending_refund=0;
	$admin_otp_pending_refund=admin_otp_refund();
	
	$deduction_retailer=show_user_av_rate($source);
	$deduction_client=show_client_av_rate($source);
	$deduction_admin=0;
	$charged=$charges=0;
	
	if($balance_retailer<$deduction_retailer && $userid!=100007)
		$err="Your Balance is low for transation.";
	if($balance_client-$balance_client_dummy+$client_otp_pending_refund<$deduction_client)
		$txn_status=41;
	if($balance_admin+$admin_otp_pending_refund<$deduction_admin)
		$txn_status=42;
	if($err=="")
	{
		$brid=0;
		$amount=0;
		$duplicate_txn=check_mt_placed($userid,$brid,$datetime,$source,$type,$method,$amount);
		$duplicate_txn=0;
		if($duplicate_txn!=0)
		{
			$err="<b>Repeated Transaction</b>:: You already had performed same transaction with same amount to this beneficiary today. If you still want to continue, kindly change transaction amount.";
		}
		else
		{
			//$err="Transaction is in progress.";
			$txn_id=$order_id=$m_id=$t_id=0;
			$user_ip=show_ip();
			$ded_ret=$deduction_retailer;
			$remain_ret=$balance_retailer-$ded_ret;
			$ded_client=$deduction_client;
			$remain_client=$balance_client-$ded_client;
			$ded_admin=$deduction_admin;
			$remain_admin=$balance_admin-$ded_admin;
			
			$qry1="";			
			$qry1="INSERT INTO $bankapi_child_txn.txn_mt_parent(date_time, retailer_id, sender, sname, receiver, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, pre_bal, amount, charges, com_charged, deducted, post_bal) value('$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret')";
			$txn_id=generate_mt_client_txn_parent($qry1);
			if($txn_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("8146145674","Txn No $txn_id started on dated $datetime_datetime");
			}
			
			$qry2="";			
			$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$deduction_retailer', '$charges', '$charged', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
			$order_id=generate_mt_client_txn_child($qry2);
			if($order_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("8146145674","Order No $order_id started on dated $datetime_datetime");
			}
			
			$qry3="";			
			$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$deduction_admin', '$charges', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
			$m_id=generate_mt_admin_txn($qry3);
			
			//update_mid_for_client
			$qry4="";
			$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
			mysql_query($qry4);
			
			//deduct_amount_for_retailer
			$qry5="";
			$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
			mysql_query($qry5);
			include_once('zf-WalletDistributed.php');
			update_user_balance($userid);
			
			//deduct_amount_for_client
			$qry6="";
			$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
			mysql_query($qry6);
			
			if($source==1)
			{
				//deduct_amount_for_admin
				$qry7="";
				$qry7="INSERT INTO $bankapi_parent_wallet.rt_eko(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
				mysql_query($qry7);
			}
			if($source==3)
			{
				//deduct_amount_for_admin
				$qry7="";
				$qry7="INSERT INTO $bankapi_parent_wallet.rt_acharya(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
				mysql_query($qry7);
			}
			if($txn_status==1 || $txn_status==3)
			{
				if($source==1)
				{
					include_once('zf-TxnSource1DmtApi.php');
					$resulted_data=add_beneficiary_with_verify($cno,$bacc,$bifsc,$bbankid);
					
					$resulted_response=$resulted_data[0];//response
					$resulted_benefid=$resulted_data[1];//benef
					$resulted_tid=$resulted_data[2];//tid
					$err=$resulted_data[3];//msg,rti,rsi,st
					if($err[2]==-1 && ($err[1]==61 || $err[1]==345))
					{
						$txn_status=2;//success
					}
					else if($err[2]==1 && $err[1]==-1)
					{
						$txn_status=-4;////failed and refund by our otp
					}
					$txn_status=3;//response awaited
					$response_message="";
					$response_message=$err[0];
					
					//update_benefid_tid_for_client_child
					$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='$resulted_benefid', tid='$resulted_tid', order_status='$txn_status' where order_id='$order_id';";
					mysql_query($qry8);
					
					//update_benefid_for_client_parent
					$qry9="update $bankapi_child_txn.txn_mt_parent set receiver_id='$resulted_benefid' where txn_id='$txn_id';";
					mysql_query($qry9);
					
					//update_benefid_tid_for_admin
					$qry10="update $bankapi_parent_txn.txn_mt set response='$resulted_response', receiver_id='$resulted_benefid', tid='$resulted_tid', mmt_status='$txn_status', response_message='$response_message' where mmt_id='$m_id';";
					mysql_query($qry10);
					
					//level wise margin for client
					
					$qry11="insert into $bankapi_child_txn.txn_mt_child_margin(order_id, txn_id, lvl_1_id, lvl_1_chg, lvl_12_id, lvl_12_chg, lcl_12_chgd) value ('$order_id', '$txn_id', '100001', '3', '$userid', '$ded_ret', '$ded_ret')";
					mysql_query($qry11);
					
					//margin for admin
					
					$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$deduction_retailer', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
					mysql_query($qry12);
				}
				else if($source==3)
				{
					include_once('zf-TxnSource3DmtApi.php');
					//$resulted_data=add_beneficiary_with_verify2($cno,$cname,$bacc,$bifsc,$pan,$aadhar,$order_id);
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					//if($resulted_data[5]!="" && $resulted_data[1]=="SUCCESS")
					//{
						$txn_status=2;
						//$resulted_response=$resulted_data[6];
						//$ASTransCode=$resulted_data[3];
						//$ReferenceNumber=$resulted_data[4];
						//$Status=$resulted_data[1];
						
						//update_benefid_tid_for_client_child
						$qry8="update $bankapi_child_txn.txn_mt_child set receiver_id='0', tid='1234', bank_ref_no='4321', order_status='$txn_status' where order_id='$order_id';";
						mysql_query($qry8);
						
						//update_benefid_for_client_parent
						$qry9="update $bankapi_child_txn.txn_mt_parent set receiver_id='0' where txn_id='$txn_id';";
						mysql_query($qry9);
						
						//update_benefid_tid_for_admin
						$qry10="update $bankapi_parent_txn.txn_mt set response='1234-4321', receiver_id='0', tid='1234', bank_ref_no='4321', mmt_status='$txn_status', response_message='1234-4321' where mmt_id='$m_id';";
						mysql_query($qry10);
						
						//level wise margin for client
						
						$qry11="insert into $bankapi_child_txn.txn_mt_child_margin(order_id, txn_id, lvl_1_id, lvl_1_chg, lvl_12_id, lvl_12_chg, lcl_12_chgd) value ('$order_id', '$txn_id', '100001', '3', '$userid', '$ded_ret', '$ded_ret')";
						mysql_query($qry11);
						
						//margin for admin
						
						$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$deduction_retailer', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
						mysql_query($qry12);
			
						$qry="insert into $bankapi_common.eko_receiver_verified(sender, bank, ifsc, receiver_acc_no, receiver_name, receiver_id_type, updated_on, source) value('$cno', '$bbname', '$bifsc', '$bacc', '$bname', '0', '$datetime_datetime', 3);";
						mysql_query($qry);
					//}
					//return $resulted_data;
				}
			}
		}
	}
	return $err;//$err;
}
function delete_beneficiary3_in_db($cno,$acc_no)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$qry="delete from $bankapi_common.eko_receiver_verified where sender='$cno' and receiver_acc_no='$acc_no' and source='3';";
	mysql_query($qry);
}
function is_verified($cno,$acc_no)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$verified=0;
	$qry="select * from $bankapi_common.eko_receiver_verified where receiver_acc_no='$acc_no' and source='1';";
	$result=mysql_query($qry);
	while($rs=mysql_fetch_array($result))
	{
		$verified=$rs['receiver_name'];
	}
	return $verified;
}
function show_verified_name_3($cno,$acc_no)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$verified="";
	$qry="select * from $bankapi_common.eko_receiver_verified where sender='$cno' and receiver_acc_no='$acc_no' and source='3';";
	$result=mysql_query($qry);
	while($rs=mysql_fetch_array($result))
	{
		$verified=$rs['receiver_name'];
	}
	return $verified;
}
function txn_fund_transfer($userid, $cno, $cname, $brid, $bno, $bname, $bbname, $bacc, $bifsc, $bbankid, $source, $type, $method, $amount, $charges123, $charged123, $doctype, $docid, $areapincode, $geo)
{
	$err="";
	$txn_status=1;
	if($charged123<$charges123)
		$charged123=$charges123;
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	
	$datetime=$datetime_datetime;
	$balance_retailer=show_txn_user_balance($userid);
	$balance_client=show_txn_client_balance();
	$balance_client_dummy=show_txn_client_dummy_balance();
	$balance_admin=show_txn_admin_balance($source);
	$client_otp_pending_refund=0;
	$admin_otp_pending_refund=0;
	$admin_otp_pending_refund=admin_otp_refund();
	
	$deduction_retailer=show_user_mt_rate($userid, $source, $method, $amount);
	$deduction_client=show_client_mt_rate($source, $amount);
	$deduction_admin=show_admin_mt_rate($source, $method, $amount);
				
	if($charges123<$deduction_retailer)
		$charges123=$deduction_retailer;
	if($charged123<$charges123)
		$charged123=$charges123;
	$deduction_retailer=$charged123;
				
	$ded_ret=$amount+$deduction_retailer;
	$remain_ret=$balance_retailer-$ded_ret;
	$ded_client=$amount+$deduction_client;
	$remain_client=$balance_client-$ded_client;
	$ded_admin=$amount+$deduction_admin;
	$remain_admin=$balance_admin-$ded_admin;
	
	if($balance_retailer<($amount+$deduction_retailer))
		$err="Your Balance is low for transation.";
	if($balance_client-$balance_client_dummy+$client_otp_pending_refund<($amount+$deduction_client))
		$txn_status=-1;
	if($balance_admin+$admin_otp_pending_refund<($amount+$deduction_admin))
		$txn_status=-2;
	if($err=="")
	{
		$duplicate_txn=check_mt_placed($userid,$brid,$datetime,$source,$type,$method,$amount);
		/*if($userid==100007)
		$duplicate_txn=0;*/
		if($duplicate_txn!=0)
		$err="repeated";
		else
		{
			//$err="Transaction is in progress.";
			$txn_id=$order_id=$m_id=$t_id=0;
			$user_ip=show_ip();
			$qry1="";			
			$qry1="INSERT INTO $bankapi_child_txn.txn_mt_parent(date_time, retailer_id, sender, sname, receiver, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, pre_bal, amount, charges, com_charged, deducted, post_bal) value('$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$amount', '$charges123', '$deduction_retailer', '$ded_ret', '$remain_ret');";
			$txn_id=generate_mt_client_txn_parent($qry1);
			if($txn_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("8146145674","Txn No $txn_id started on dated $datetime_datetime");
			}
			
			$limit=5000;
			$amt=$amount;
			$done_charges=0;
			while($amt>=$limit)
			{
				sleep(1);
				$order_id=$m_id=$t_id=0;
				$amt=$amt-$limit;
			
				$balance_retailer=show_txn_user_balance($userid);
				$balance_client=show_txn_client_balance();
				$balance_admin=show_txn_admin_balance($source);
				
				$deduction_retailer=show_user_mt_rate($userid, $source, $method, $limit);
				$deduction_client=show_client_mt_rate($source, $limit);
				$deduction_admin=show_admin_mt_rate($source, $method, $limit);
				
				if($charges123!=$charged123)
				{
					$charges2=0;
					if($charges2<$deduction_retailer)
						$charges2=$deduction_retailer;
					$deduction_retailer=$limit*$charged123/$amount;
				}
				else
				{
					$charges2=$deduction_retailer;
				}
				
				$ded_ret=$limit+$deduction_retailer;
				$remain_ret=$balance_retailer-$ded_ret;
				$ded_client=$limit+$deduction_client;
				$remain_client=$balance_client-$ded_client;
				$ded_admin=$limit+$deduction_admin;
				$remain_admin=$balance_admin-$ded_admin;
				$done_charges+=$deduction_retailer;
				////////////////////do with $limit
				$qry2="";			
				$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$limit', '$charges2', '$deduction_retailer', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
				$order_id=generate_mt_client_txn_child($qry2);
				if($order_id%1000==0)
				{
					//include_once('../functions/_zsms.php');
					//zsms("8146145674","Order No $order_id started on dated $datetime_datetime");
				}
				
				$qry3="";			
				$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$limit', '$deduction_admin', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
				$m_id=generate_mt_admin_txn($qry3);
				
				//update_mid_for_client
				$qry4="";
				$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
				mysql_query($qry4);
				
				//deduct_amount_for_retailer
				$qry5="";
				$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
				mysql_query($qry5);
				include_once('zf-WalletDistributed.php');
				update_user_balance($userid);
				
				//deduct_amount_for_client
				$qry6="";
				$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
				mysql_query($qry6);
				
				if($source==1)
				{
					//deduct_amount_for_admin
					$qry7="";
					$qry7="INSERT INTO $bankapi_parent_wallet.rt_eko(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
					mysql_query($qry7);
				}
				if($txn_status>0)
				{	
					include_once('zf-TxnSource1DmtApi.php');
					$resulted_data=fund_transfer($m_id,$cno,$brid,$method,$limit,$doctype,$docid,$areapincode,$geo);
					$resulted_response=$resulted_bankrefno=$resulted_tid=$resulted_message=$resulted_type_id=$resulted_status_id=$resulted_status=$resulted_status_desc="";
					$resulted_response=$resulted_data[0];
					$resulted_bankrefno=$resulted_data[1];
					$resulted_tid=$resulted_data[2];
					$resulted_message=$resulted_data[3];
					$resulted_type_id=$resulted_data[4];
					$resulted_status_id=$resulted_data[5];
					$resulted_status=$resulted_data[6];
					$resulted_status_desc=$resulted_data[7];
					if($resulted_status_id==0 && ($resulted_type_id==70 || $resulted_type_id==325))
					{
						if($resulted_status==0)
							$txn_status=2;//success
						else if($resulted_status==1)
							$txn_status=-4;//failed and refund by our otp
						else if($resulted_status==2 && $resulted_status_desc=="Response Awaited")
							$txn_status=3;//Response Awaited
						else if($resulted_status==2 && $resulted_status_desc=="Initiated")
							$txn_status=1;//Initiated
						else if($resulted_status==3)
							$txn_status=4;//Refund Pending
						else if($resulted_status==4)
							$txn_status=5;//Refunded
						else if($resulted_status==5)
							$txn_status=3;//Hold
						else if($resulted_status==8)
							$txn_status=3;//Scheduled
					}
					
					//update tid for client_child
					mysql_query("update $bankapi_child_txn.txn_mt_child set tid='$resulted_tid', bank_ref_no='$resulted_bankrefno', order_status='$txn_status' where order_id='$order_id';");
					
					//update response/tid for admin
					mysql_query("update $bankapi_parent_txn.txn_mt set response='$resulted_response', bank_ref_no='$resulted_bankrefno', tid='$resulted_tid', response_message='$resulted_message', mmt_status='$txn_status' where mmt_id='$m_id';");
				}
	$parents=show_my_parents($userid);
	$parent_01=$parents[0];
	$parent_02=$parents[1];
	$parent_03=$parents[2];
	$parent_04=$parents[3];
	$parent_05=$parents[4];
	$parent_06=$parents[5];
	$parent_07=$parents[6];
	$parent_08=$parents[7];
	$parent_09=$parents[8];
	$parent_10=$parents[9];
	$parent_11=$parents[10];
	$parent_12=$parents[11];
	
	$parent_01_rate=show_user_mt_rate($parent_01, $source, $method, $limit);
	$parent_02_rate=show_user_mt_rate($parent_02, $source, $method, $limit);
	$parent_03_rate=show_user_mt_rate($parent_03, $source, $method, $limit);
	$parent_04_rate=show_user_mt_rate($parent_04, $source, $method, $limit);
	$parent_05_rate=show_user_mt_rate($parent_05, $source, $method, $limit);
	$parent_06_rate=show_user_mt_rate($parent_06, $source, $method, $limit);
	$parent_07_rate=show_user_mt_rate($parent_07, $source, $method, $limit);
	$parent_08_rate=show_user_mt_rate($parent_08, $source, $method, $limit);
	$parent_09_rate=show_user_mt_rate($parent_09, $source, $method, $limit);
	$parent_10_rate=show_user_mt_rate($parent_10, $source, $method, $limit);
	$parent_11_rate=show_user_mt_rate($parent_11, $source, $method, $limit);
	$parent_12_rate=show_user_mt_rate($parent_12, $source, $method, $limit);
				
				//level wise margin for client
				
				$qry11="insert into $bankapi_child_txn.txn_mt_child_margin value ('$order_id', '$txn_id', '$parent_01', '$parent_01_rate', '$parent_02', '$parent_02_rate', '$parent_03', '$parent_03_rate', '$parent_04', '$parent_04_rate', '$parent_05', '$parent_05_rate', '$parent_06', '$parent_06_rate', '$parent_07', '$parent_07_rate', '$parent_08', '$parent_08_rate', '$parent_09', '$parent_09_rate', '$parent_10', '$parent_10_rate', '$parent_11', '$parent_11_rate', '$parent_12', '$parent_12_rate', '$deduction_retailer')";
				mysql_query($qry11);
				
				//margin for admin
				
				$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$limit', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
				mysql_query($qry12);
			}
			if($amt<$limit && $amt>0)
			{
				sleep(1);
				$balance_retailer=show_txn_user_balance($userid);
				$balance_client=show_txn_client_balance();
				$balance_admin=show_txn_admin_balance($source);
				
				$deduction_retailer=show_user_mt_rate($userid, $source, $method, $amt);
				$deduction_client=show_client_mt_rate($source, $amt);
				$deduction_admin=show_admin_mt_rate($source, $method, $amt);
				$charges2=0;
				if($charges2<$deduction_retailer)
					$charges2=$deduction_retailer;
				$deduction_retailer=$amt*$charged123/$amount;
				$deduction_retailer=$charged123-$done_charges;
				
				$ded_ret=$amt+$deduction_retailer;
				$remain_ret=$balance_retailer-$ded_ret;
				$ded_client=$amt+$deduction_client;
				$remain_client=$balance_client-$ded_client;
				$ded_admin=$amt+$deduction_admin;
				$remain_admin=$balance_admin-$ded_admin;
				////////////////////do with $amt
				$qry2="";			
				$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$amt', '$charges2', '$deduction_retailer', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
				$order_id=generate_mt_client_txn_child($qry2);
				if($order_id%1000==0)
				{
					//include_once('../functions/_zsms.php');
					//zsms("8146145674","Order No $order_id started on dated $datetime_datetime");
				}
				
				$qry3="";			
				$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$amt', '$deduction_admin', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
				$m_id=generate_mt_admin_txn($qry3);
				
				//update_mid_for_client
				$qry4="";
				$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
				mysql_query($qry4);
				
				//deduct_amount_for_retailer
				$qry5="";
				$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
				mysql_query($qry5);
				include_once('zf-WalletDistributed.php');
				update_user_balance($userid);
				
				//deduct_amount_for_client
				$qry6="";
				$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
				mysql_query($qry6);
				
				if($source==1)
				{
					//deduct_amount_for_admin
					$qry7="";
					$qry7="INSERT INTO $bankapi_parent_wallet.rt_eko(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
					mysql_query($qry7);
				}
				if($txn_status>0)
				{	
					include_once('zf-TxnSource1DmtApi.php');
					$resulted_data=fund_transfer($m_id,$cno,$brid,$method,$amt,$doctype,$docid,$areapincode,$geo);
					$resulted_response=$resulted_bankrefno=$resulted_tid=$resulted_message=$resulted_type_id=$resulted_status_id=$resulted_status=$resulted_status_desc="";
					$resulted_response=$resulted_data[0];
					$resulted_bankrefno=$resulted_data[1];
					$resulted_tid=$resulted_data[2];
					$resulted_message=$resulted_data[3];
					if($resulted_status_id==0 && ($resulted_type_id==70 || $resulted_type_id==325))
					{
						if($resulted_status==0)
							$txn_status=2;//success
						else if($resulted_status==1)
							$txn_status=-4;//failed and refund by our otp
						else if($resulted_status==2 && $resulted_status_desc=="Response Awaited")
							$txn_status=3;//Response Awaited
						else if($resulted_status==2 && $resulted_status_desc=="Initiated")
							$txn_status=1;//Initiated
						else if($resulted_status==3)
							$txn_status=4;//Refund Pending
						else if($resulted_status==4)
							$txn_status=5;//Refunded
						else if($resulted_status==5)
							$txn_status=3;//Hold
						else if($resulted_status==8)
							$txn_status=3;//Scheduled
					}
					
					//update tid for client_child
					mysql_query("update $bankapi_child_txn.txn_mt_child set tid='$resulted_tid', bank_ref_no='$resulted_bankrefno', order_status='$txn_status' where order_id='$order_id';");
					
					//update response/tid for admin
					mysql_query("update $bankapi_parent_txn.txn_mt set response='$resulted_response', bank_ref_no='$resulted_bankrefno', tid='$resulted_tid', response_message='$resulted_message', mmt_status='$txn_status' where mmt_id='$m_id';");
				}
			
	$parents=show_my_parents($userid);
	$parent_01=$parents[0];
	$parent_02=$parents[1];
	$parent_03=$parents[2];
	$parent_04=$parents[3];
	$parent_05=$parents[4];
	$parent_06=$parents[5];
	$parent_07=$parents[6];
	$parent_08=$parents[7];
	$parent_09=$parents[8];
	$parent_10=$parents[9];
	$parent_11=$parents[10];
	$parent_12=$parents[11];
	
	$parent_01_rate=show_user_mt_rate($parent_01, $source, $method, $amt);
	$parent_02_rate=show_user_mt_rate($parent_02, $source, $method, $amt);
	$parent_03_rate=show_user_mt_rate($parent_03, $source, $method, $amt);
	$parent_04_rate=show_user_mt_rate($parent_04, $source, $method, $amt);
	$parent_05_rate=show_user_mt_rate($parent_05, $source, $method, $amt);
	$parent_06_rate=show_user_mt_rate($parent_06, $source, $method, $amt);
	$parent_07_rate=show_user_mt_rate($parent_07, $source, $method, $amt);
	$parent_08_rate=show_user_mt_rate($parent_08, $source, $method, $amt);
	$parent_09_rate=show_user_mt_rate($parent_09, $source, $method, $amt);
	$parent_10_rate=show_user_mt_rate($parent_10, $source, $method, $amt);
	$parent_11_rate=show_user_mt_rate($parent_11, $source, $method, $amt);
	$parent_12_rate=show_user_mt_rate($parent_12, $source, $method, $amt);
				
				//level wise margin for client
				
				$qry11="insert into $bankapi_child_txn.txn_mt_child_margin value ('$order_id', '$txn_id', '$parent_01', '$parent_01_rate', '$parent_02', '$parent_02_rate', '$parent_03', '$parent_03_rate', '$parent_04', '$parent_04_rate', '$parent_05', '$parent_05_rate', '$parent_06', '$parent_06_rate', '$parent_07', '$parent_07_rate', '$parent_08', '$parent_08_rate', '$parent_09', '$parent_09_rate', '$parent_10', '$parent_10_rate', '$parent_11', '$parent_11_rate', '$parent_12', '$parent_12_rate', '$deduction_retailer')";
				mysql_query($qry11);
				
				//margin for admin
				
				$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$amt', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
				mysql_query($qry12);
			}
		}
	}
	return $err;
}

function txn_fund_transfer3($userid, $cno, $cname, $brid, $bno, $bname, $bbname, $bacc, $bifsc, $bbankid, $source, $type, $method, $amount, $charges123, $charged123, $pan, $aadhar)//, $doctype, $docid, $areapincode, $geo
{
	$err="";
	$txn_status=1;
	if($charged123<$charges123)
		$charged123=$charges123;
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	
	$datetime=$datetime_datetime;
	$balance_retailer=show_txn_user_balance($userid);
	$balance_client=show_txn_client_balance();
	$balance_client_dummy=show_txn_client_dummy_balance();
	$balance_admin=show_txn_admin_balance($source);
	$client_otp_pending_refund=0;
	$admin_otp_pending_refund=0;
	$admin_otp_pending_refund=admin_otp_refund();
	
	$deduction_retailer=show_user_mt_rate($userid, $source, $method, $amount);
	$deduction_client=show_client_mt_rate($source, $amount);
	$deduction_admin=show_admin_mt_rate($source, $method, $amount);
				
	if($charges123<$deduction_retailer)
		$charges123=$deduction_retailer;
	if($charged123<$charges123)
		$charged123=$charges123;
	$deduction_retailer=$charged123;
				
	$ded_ret=$amount+$deduction_retailer;
	$remain_ret=$balance_retailer-$ded_ret;
	$ded_client=$amount+$deduction_client;
	$remain_client=$balance_client-$ded_client;
	$ded_admin=$amount+$deduction_admin;
	$remain_admin=$balance_admin-$ded_admin;
	
	if($balance_retailer<($amount+$deduction_retailer))
		$err="Your Balance is low for transation.";
	if($balance_client-$balance_client_dummy+$client_otp_pending_refund<($amount+$deduction_client))
		$txn_status=-1;
	if($balance_admin+$admin_otp_pending_refund<($amount+$deduction_admin))
		$txn_status=-2;
	if($err=="")
	{
		$duplicate_txn=check_mt_placed($userid,$brid,$datetime,$source,$type,$method,$amount);
		/*if($userid==100007)
		$duplicate_txn=0;*/
		if($duplicate_txn!=0)
		$err="repeated";
		else
		{
			//$err="Transaction is in progress.";
			$txn_id=$order_id=$m_id=$t_id=0;
			$user_ip=show_ip();
			$qry1="";			
			$qry1="INSERT INTO $bankapi_child_txn.txn_mt_parent(date_time, retailer_id, sender, sname, receiver, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, pre_bal, amount, charges, com_charged, deducted, post_bal) value('$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$amount', '$charges123', '$deduction_retailer', '$ded_ret', '$remain_ret');";
			$txn_id=generate_mt_client_txn_parent($qry1);
			if($txn_id%1000==0)
			{
				//include_once('../functions/_zsms.php');
				//zsms("8146145674","Txn No $txn_id started on dated $datetime_datetime");
			}
			
			$limit=5000;
			$amt=$amount;
			$done_charges=0;
			while($amt>=$limit)
			{
				sleep(1);
				$order_id=$m_id=$t_id=0;
				$amt=$amt-$limit;
			
				$balance_retailer=show_txn_user_balance($userid);
				$balance_client=show_txn_client_balance();
				$balance_admin=show_txn_admin_balance($source);
				
				$deduction_retailer=show_user_mt_rate($userid, $source, $method, $limit);
				$deduction_client=show_client_mt_rate($source, $limit);
				$deduction_admin=show_admin_mt_rate($source, $method, $limit);
				
				if($charges123!=$charged123)
				{
					$charges2=0;
					if($charges2<$deduction_retailer)
						$charges2=$deduction_retailer;
					$deduction_retailer=$limit*$charged123/$amount;
				}
				else
				{
					$charges2=$deduction_retailer;
				}
				
				$ded_ret=$limit+$deduction_retailer;
				$remain_ret=$balance_retailer-$ded_ret;
				$ded_client=$limit+$deduction_client;
				$remain_client=$balance_client-$ded_client;
				$ded_admin=$limit+$deduction_admin;
				$remain_admin=$balance_admin-$ded_admin;
				$done_charges+=$deduction_retailer;
				////////////////////do with $limit
				$qry2="";			
				$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$limit', '$charges2', '$deduction_retailer', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
				$order_id=generate_mt_client_txn_child($qry2);
				if($order_id%1000==0)
				{
					//include_once('../functions/_zsms.php');
					//zsms("8146145674","Order No $order_id started on dated $datetime_datetime");
				}
				
				$qry3="";			
				$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$limit', '$deduction_admin', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
				$m_id=generate_mt_admin_txn($qry3);
				
				//update_mid_for_client
				$qry4="";
				$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
				mysql_query($qry4);
				
				//deduct_amount_for_retailer
				$qry5="";
				$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
				mysql_query($qry5);
				include_once('zf-WalletDistributed.php');
				update_user_balance($userid);
				
				//deduct_amount_for_client
				$qry6="";
				$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
				mysql_query($qry6);
				
				if($source==3)
				{
					//deduct_amount_for_admin
					$qry7="";
					$qry7="INSERT INTO $bankapi_parent_wallet.rt_acharya(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
					mysql_query($qry7);
				}
				if($txn_status>0)
				{	
					include_once('zf-TxnSource3DmtApi.php');
/////LOKESH
					$resulted_data=fund_transfer2($m_id,$cno,$cname,$brid,$bacc,$bifsc,$method,$limit,$pan,$aadhar);
					$resulted_response=$resulted_data[6];
					$ASTransCode=$resulted_data[3];
					$ReferenceNumber=$resulted_data[4];
					$Status=$resulted_data[1];
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					if($resulted_data[1]=='SUCCESS')
						$txn_status=2;
					else if($resulted_data[1]=='FAILED')
						$txn_status=-4;
					
					//update tid for client_child
					mysql_query("update $bankapi_child_txn.txn_mt_child set tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';");
					
					//update response/tid for admin
					mysql_query("update $bankapi_parent_txn.txn_mt set response='$resulted_response', bank_ref_no='$ReferenceNumber', tid='$ASTransCode', response_message='$Status', mmt_status='$txn_status' where mmt_id='$m_id';");
				}
	$parents=show_my_parents($userid);
	$parent_01=$parents[0];
	$parent_02=$parents[1];
	$parent_03=$parents[2];
	$parent_04=$parents[3];
	$parent_05=$parents[4];
	$parent_06=$parents[5];
	$parent_07=$parents[6];
	$parent_08=$parents[7];
	$parent_09=$parents[8];
	$parent_10=$parents[9];
	$parent_11=$parents[10];
	$parent_12=$parents[11];
	
	$parent_01_rate=show_user_mt_rate($parent_01, $source, $method, $limit);
	$parent_02_rate=show_user_mt_rate($parent_02, $source, $method, $limit);
	$parent_03_rate=show_user_mt_rate($parent_03, $source, $method, $limit);
	$parent_04_rate=show_user_mt_rate($parent_04, $source, $method, $limit);
	$parent_05_rate=show_user_mt_rate($parent_05, $source, $method, $limit);
	$parent_06_rate=show_user_mt_rate($parent_06, $source, $method, $limit);
	$parent_07_rate=show_user_mt_rate($parent_07, $source, $method, $limit);
	$parent_08_rate=show_user_mt_rate($parent_08, $source, $method, $limit);
	$parent_09_rate=show_user_mt_rate($parent_09, $source, $method, $limit);
	$parent_10_rate=show_user_mt_rate($parent_10, $source, $method, $limit);
	$parent_11_rate=show_user_mt_rate($parent_11, $source, $method, $limit);
	$parent_12_rate=show_user_mt_rate($parent_12, $source, $method, $limit);
				
				//level wise margin for client
				
				$qry11="insert into $bankapi_child_txn.txn_mt_child_margin value ('$order_id', '$txn_id', '$parent_01', '$parent_01_rate', '$parent_02', '$parent_02_rate', '$parent_03', '$parent_03_rate', '$parent_04', '$parent_04_rate', '$parent_05', '$parent_05_rate', '$parent_06', '$parent_06_rate', '$parent_07', '$parent_07_rate', '$parent_08', '$parent_08_rate', '$parent_09', '$parent_09_rate', '$parent_10', '$parent_10_rate', '$parent_11', '$parent_11_rate', '$parent_12', '$parent_12_rate', '$deduction_retailer')";
				mysql_query($qry11);
				
				//margin for admin
				
				$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$limit', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
				mysql_query($qry12);
			}
			if($amt<$limit && $amt>0)
			{
				sleep(1);
				$balance_retailer=show_txn_user_balance($userid);
				$balance_client=show_txn_client_balance();
				$balance_admin=show_txn_admin_balance($source);
				
				$deduction_retailer=show_user_mt_rate($userid, $source, $method, $amt);
				$deduction_client=show_client_mt_rate($source, $amt);
				$deduction_admin=show_admin_mt_rate($source, $method, $amt);
				$charges2=0;
				if($charges2<$deduction_retailer)
					$charges2=$deduction_retailer;
				$deduction_retailer=$amt*$charged123/$amount;
				$deduction_retailer=$charged123-$done_charges;
				
				$ded_ret=$amt+$deduction_retailer;
				$remain_ret=$balance_retailer-$ded_ret;
				$ded_client=$amt+$deduction_client;
				$remain_client=$balance_client-$ded_client;
				$ded_admin=$amt+$deduction_admin;
				$remain_admin=$balance_admin-$ded_admin;
				////////////////////do with $amt
				$qry2="";			
				$qry2="INSERT INTO $bankapi_child_txn.txn_mt_child(txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, com_charged, deducted, bal_after, updated_on, order_status, ip) value ('$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_retailer', '$amt', '$charges2', '$deduction_retailer', '$ded_ret', '$remain_ret', '$datetime', '$txn_status', '$user_ip')";
				$order_id=generate_mt_client_txn_child($qry2);
				if($order_id%1000==0)
				{
					//include_once('../functions/_zsms.php');
					//zsms("8146145674","Order No $order_id started on dated $datetime_datetime");
				}
				
				$qry3="";			
				$qry3="INSERT INTO $bankapi_parent_txn.txn_mt(client_id, order_id, txn_id, created_on, user_id, sender_number, sname, receiver_number, receiver_id, rname, rbname, racc, rifsc, rbankid, source, type, method, bal_before, amount, charges, bal_after, updated_on, mmt_status, ip) value('$clientdbid', '$order_id', '$txn_id', '$datetime', '$userid', '$cno', '$cname', '$bno', '$brid', '$bname', '$bbname', '$bacc', '$bifsc', '$bbankid', '$source', '$type', '$method', '$balance_admin', '$amt', '$deduction_admin', '$remain_admin', '$datetime', '$txn_status', '$user_ip')";
				$m_id=generate_mt_admin_txn($qry3);
				
				//update_mid_for_client
				$qry4="";
				$qry4="update $bankapi_child_txn.txn_mt_child set mid='$m_id' where order_id='$order_id';";
				mysql_query($qry4);
				
				//deduct_amount_for_retailer
				$qry5="";
				$qry5="INSERT INTO $bankapi_child_wallet.distribution(wallet_date, wallet_time, user_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '6', 'Money Transfer Order No. $order_id', '$balance_retailer', '0', '$ded_ret', '$remain_ret', 'Money Transfer Order generated by user at $datetime_datetime')";
				mysql_query($qry5);
				include_once('zf-WalletDistributed.php');
				update_user_balance($userid);
				
				//deduct_amount_for_client
				$qry6="";
				$qry6="INSERT INTO $bankapi_child_wallet.realtime(wallet_date, wallet_time, user_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$userid', '101', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid', '$balance_client', '0', '$ded_client', '$remain_client')";
				mysql_query($qry6);
				
				if($source==3)
				{
					//deduct_amount_for_admin
					$qry7="";
					$qry7="INSERT INTO $bankapi_parent_wallet.rt_acharya(wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) value('$datetime_date', '$datetime_time', '$clientdbid', '$userid', '$order_id', '$m_id', '2', 'Money Transfer Order No. $order_id generated by user id $userid of client id $clientdbid', '$balance_admin', '0', '$ded_admin', '$remain_admin')";
					mysql_query($qry7);
				}
				if($txn_status>0)
				{	
					include_once('zf-TxnSource3DmtApi.php');
/////LOKESH
					$resulted_data=fund_transfer2($m_id,$cno,$cname,$brid,$bacc,$bifsc,$method,$amt,$pan,$aadhar);
					$resulted_response=$resulted_data[6];
					$ASTransCode=$resulted_data[3];
					$ReferenceNumber=$resulted_data[4];
					$Status=$resulted_data[1];
					//$StatusCode,$Status,$Description,$ASTransCode,$ReferenceNumber,$BeneficiaryName,$response
					if($resulted_data[1]=='SUCCESS')
						$txn_status=2;
					else if($resulted_data[1]=='FAILED')
						$txn_status=-4;
					
					//update tid for client_child
					mysql_query("update $bankapi_child_txn.txn_mt_child set tid='$ASTransCode', bank_ref_no='$ReferenceNumber', order_status='$txn_status' where order_id='$order_id';");
					
					//update response/tid for admin
					mysql_query("update $bankapi_parent_txn.txn_mt set response='$resulted_response', bank_ref_no='$ReferenceNumber', tid='$ASTransCode', response_message='$Status', mmt_status='$txn_status' where mmt_id='$m_id';");
				}
			
	$parents=show_my_parents($userid);
	$parent_01=$parents[0];
	$parent_02=$parents[1];
	$parent_03=$parents[2];
	$parent_04=$parents[3];
	$parent_05=$parents[4];
	$parent_06=$parents[5];
	$parent_07=$parents[6];
	$parent_08=$parents[7];
	$parent_09=$parents[8];
	$parent_10=$parents[9];
	$parent_11=$parents[10];
	$parent_12=$parents[11];
	
	$parent_01_rate=show_user_mt_rate($parent_01, $source, $method, $amt);
	$parent_02_rate=show_user_mt_rate($parent_02, $source, $method, $amt);
	$parent_03_rate=show_user_mt_rate($parent_03, $source, $method, $amt);
	$parent_04_rate=show_user_mt_rate($parent_04, $source, $method, $amt);
	$parent_05_rate=show_user_mt_rate($parent_05, $source, $method, $amt);
	$parent_06_rate=show_user_mt_rate($parent_06, $source, $method, $amt);
	$parent_07_rate=show_user_mt_rate($parent_07, $source, $method, $amt);
	$parent_08_rate=show_user_mt_rate($parent_08, $source, $method, $amt);
	$parent_09_rate=show_user_mt_rate($parent_09, $source, $method, $amt);
	$parent_10_rate=show_user_mt_rate($parent_10, $source, $method, $amt);
	$parent_11_rate=show_user_mt_rate($parent_11, $source, $method, $amt);
	$parent_12_rate=show_user_mt_rate($parent_12, $source, $method, $amt);
				
				//level wise margin for client
				
				$qry11="insert into $bankapi_child_txn.txn_mt_child_margin value ('$order_id', '$txn_id', '$parent_01', '$parent_01_rate', '$parent_02', '$parent_02_rate', '$parent_03', '$parent_03_rate', '$parent_04', '$parent_04_rate', '$parent_05', '$parent_05_rate', '$parent_06', '$parent_06_rate', '$parent_07', '$parent_07_rate', '$parent_08', '$parent_08_rate', '$parent_09', '$parent_09_rate', '$parent_10', '$parent_10_rate', '$parent_11', '$parent_11_rate', '$parent_12', '$parent_12_rate', '$deduction_retailer')";
				mysql_query($qry11);
				
				//margin for admin
				
				$qry12="insert into $bankapi_parent_txn.txn_mt_margin(mt_id, created_on, client_id, source_id, type, method, service_id, amount, admin_rate, client_rate, admin_comm) value ('$m_id', '$datetime_datetime', '$clientdbid', '$source', '$type', '$method', '101', '$amt', '$deduction_admin', '$deduction_client', $deduction_client-$deduction_admin)";
				mysql_query($qry12);
			}
		}
	}
	return $err;
}

function mid_by_order($order)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	
	$mid=0;
	$query="SELECT * FROM $bankapi_child_txn.txn_mt_child where order_id='$order';";
	$result=mysql_query($query);
	while($r = mysql_fetch_array($result)) 
	{
		$mid=$r['mid'];
	}
	return $mid;
}

function show_ip()
{
	$ipaddress1 = "";
	if (isset($_SERVER['HTTP_CLIENT_IP']))//check ip from share internet
		$ipaddress1 = $_SERVER['HTTP_CLIENT_IP'];
	else if(isset($_SERVER['HTTP_X_FORWARDED_FOR']))//to check ip is pass from proxy
		$ipaddress1 = $_SERVER['HTTP_X_FORWARDED_FOR'];
	else if(isset($_SERVER['HTTP_X_FORWARDED']))
		$ipaddress1 = $_SERVER['HTTP_X_FORWARDED'];
	else if(isset($_SERVER['HTTP_FORWARDED_FOR']))
		$ipaddress1 = $_SERVER['HTTP_FORWARDED_FOR'];
	else if(isset($_SERVER['HTTP_FORWARDED']))
		$ipaddress1 = $_SERVER['HTTP_FORWARDED'];
	else if(isset($_SERVER['REMOTE_ADDR']))
		$ipaddress1 = $_SERVER['REMOTE_ADDR'];
	else
		$ipaddress1 = 'UNKNOWN';
		
		
	$ipaddress2 = "";
	if (getenv('HTTP_CLIENT_IP'))//check ip from share internet
		$ipaddress2 = getenv('HTTP_CLIENT_IP');
	else if(getenv('HTTP_X_FORWARDED_FOR'))//to check ip is pass from proxy
		$ipaddress2 = getenv('HTTP_X_FORWARDED_FOR');
	else if(getenv('HTTP_X_FORWARDED'))
		$ipaddress2 = getenv('HTTP_X_FORWARDED');
	else if(getenv('HTTP_FORWARDED_FOR'))
		$ipaddress2 = getenv('HTTP_FORWARDED_FOR');
	else if(getenv('HTTP_FORWARDED'))
		$ipaddress2 = getenv('HTTP_FORWARDED');
	else if(getenv('REMOTE_ADDR'))
		$ipaddress2 = getenv('REMOTE_ADDR');
	else
		$ipaddress2 = 'UNKNOWN';
		
	$final_ip=$ipaddress1."<br>".$ipaddress2;
	$browser=$_SERVER['HTTP_USER_AGENT'];
	
	$main_ip="$final_ip <br><br> $browser";
	return $main_ip;
}

function generate_mt_client_txn_parent($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_mt_client_txn_child($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_mt_admin_txn($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_rc_client_txn($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function generate_rc_admin_txn($query)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	$generated_id=0;
	mysql_query($query);				
	$generated_id=mysql_insert_id();
	return $generated_id;
}

function refund_amount($oid,$mid,$tid,$refund_source_tid,$source)
{
	require('zc-gyan-info-admin.php');
	require('zc-commons-admin.php');
	include_once('zf-WalletsMarginsForTxn.php');
	include_once('zf-WalletDistributed.php');
	// start refund to refund_source_tid//refund_admin_tid//refund_client_tid//refund_retailer_tid
	// get user id of order id
	$uid=0;
	$admin_charges=0;
	$client_charges=0;
	$retailer_charges=0;
	$qry3="select * from $bankapi_parent_txn.txn_mt where mmt_id='$mid'";
	$res3=mysql_query($qry3);
	while($rs3=mysql_fetch_array($res3))
	{
		$uid=$rs3['user_id'];
	}
	
	// get order deducted amount of admin wallet with wallet id
	if($source==1)
	{
		$query_ref="select * from $bankapi_parent_wallet.rt_eko where user_id='$uid' and client_id='$clientdbid' and client_order_id='$oid' and transaction_type='2' order by wallet_id desc limit 0,1";
		$result_ref=mysql_query($query_ref);
		while($rs_ref = mysql_fetch_assoc($result_ref))
		{
			$admin_charges=$rs_ref['amount_dr'];
		}
	}
	if($source==3)
	{
		$query_ref="select * from $bankapi_parent_wallet.rt_acharya where user_id='$uid' and client_id='$clientdbid' and client_order_id='$oid' and transaction_type='2' order by wallet_id desc limit 0,1";
		$result_ref=mysql_query($query_ref);
		while($rs_ref = mysql_fetch_assoc($result_ref))
		{
			$admin_charges=$rs_ref['amount_dr'];
		}
	}
	
	// get order deducted amount of client wallet with wallet id
	$query_ref="select * from $bankapi_child_wallet.realtime where user_id='$uid' and client_order_id='$oid' and transaction_type='2' order by wallet_id desc limit 0,1";
	$result_ref=mysql_query($query_ref);
	while($rs_ref = mysql_fetch_assoc($result_ref))
	{
		$client_charges=$rs_ref['amount_dr'];
	}
	
	// get order deducted amount of user wallet with wallet id
	$field="request_id";
	if($mid>58292)
		$field="order_id";
	$query_ref="select * from $bankapi_child_wallet.distribution where user_id='$uid' and user_id2='0' and $field='$oid' and transaction_type='6'";
	$result_ref=mysql_query($query_ref);
	while($rs_ref = mysql_fetch_assoc($result_ref))
	{
		$retailer_charges=$rs_ref['amount_dr'];
	}
	
	$filled_remarks="Money Transfer order $oid refunded";
	//get last balance of admin
	$balance_admin=show_txn_admin_balance($source);
	$balance_admin_new=$balance_admin+$admin_charges;
	
	if($source==1)
	{
		//refund order to admin
		$query4b="INSERT INTO $bankapi_parent_wallet.rt_eko (wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) VALUES ('$datetime_date', '$datetime_time', '$clientdbid', '$uid', '$oid', '0', '3', '$filled_remarks', '$balance_admin', '$admin_charges', '0.00', '$balance_admin_new');";
		mysql_query($query4b);
		$refund_admin_tid=mysql_insert_id();
	}
	if($source==3)
	{
		//refund order to admin
		$query4b="INSERT INTO $bankapi_parent_wallet.rt_acharya (wallet_date, wallet_time, client_id, user_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) VALUES ('$datetime_date', '$datetime_time', '$clientdbid', '$uid', '$oid', '0', '3', '$filled_remarks', '$balance_admin', '$admin_charges', '0.00', '$balance_admin_new');";
		mysql_query($query4b);
		$refund_admin_tid=mysql_insert_id();
	}
	
	//get last balance of client
	$balance_client=show_txn_client_balance();
	$balance_client_new=$balance_client+$client_charges;
	//refund order to client
	$query4b="INSERT INTO $bankapi_child_wallet.realtime (wallet_date, wallet_time, user_id, request_id, service_id, client_order_id, source_order_id, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal) VALUES ('$datetime_date', '$datetime_time', '$uid', '0', '101', '$oid', '0', '3', '$filled_remarks', '$balance_client', '$client_charges', '0.00', '$balance_client_new');";
	mysql_query($query4b);
	$refund_client_tid=mysql_insert_id();
	
	//get last balance of retailer
	$balance_retailer=show_txn_user_balance($uid);
	$balance_retailer_new=$balance_retailer+$retailer_charges;
	//refund order to retailer
	$query4b="INSERT INTO $bankapi_child_wallet.distribution (wallet_date, wallet_time, user_id, user_id2, request_id, service_id, order_id, tid, transaction_type, transaction_description, amount_pre, amount_cr, amount_dr, amount_bal, remarks) VALUES ('$datetime_date', '$datetime_time', '$uid', '0', '0', '101', '$oid', '$mid', '7', '$filled_remarks', '$balance_retailer', '$retailer_charges', '0.00', '$balance_retailer_new', '$filled_remarks at $datetime_datetime');";
	mysql_query($query4b);
	$refund_retailer_tid=mysql_insert_id();
	update_user_balance($uid);

	// update order status to refunded for admin
	$qry1="update $bankapi_parent_txn.txn_mt set mmt_status='5', refund_source_tid='$refund_source_tid', refund_admin_tid='$refund_admin_tid', refund_client_tid='$refund_client_tid', refund_retailer_tid='$refund_retailer_tid', updated_on='$datetime_datetime' where mmt_id='$mid'";
	mysql_query($qry1);	
	// update order status to refunded for client
	$qry2="update $bankapi_child_txn.txn_mt_child set order_status='5', refund_source_tid='$refund_source_tid', refund_admin_tid='$refund_admin_tid', refund_client_tid='$refund_client_tid', refund_retailer_tid='$refund_retailer_tid', updated_on='$datetime_datetime' where order_id='$oid'";
	mysql_query($qry2);	
}
?>