<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<?php include('_head-tag.php'); ?>
</head>
<body class="cyan-scheme">
<div id="form1">

    <!--Page load animation-->
 
    <div class="wrapper vertical-sidebar" id="full-page">
        <?php include('_nav-menu.php'); ?>

        <main id="content">
            <div id="page-content">

                
      <div class="row content-container elements">
        <div class="col s12 m12 l6 socialMessage">
            
                <div class="card ">
                    <div class="card-content">
                        <h5><i class="fa fa-support fa-1x"></i> My Ticket</h5>
                    </div>
					<div class="card-action">
                        <div class="row extra-elements">
						<?php
									$tid="";
									if(isset($_REQUEST['tid']))
									$tid=$_REQUEST['tid'];
									if($tid!="")
									{
										$query4a="select * from child_tickets where user_id='$user_id' and  ticket_id='$tid';";
										$result4a=mysql_query($query4a);
										include '../functions/_my_uname.php';
										while($rs=mysql_fetch_assoc($result4a))
										{
											$tids=$rs['ticket_id'];
											$uid=$rs['user_id'];
											$uids=show_my_uname($rs['user_id']);
											$tdate=$rs['date_time'];
											$ttype=$rs['ticket_type'];
											if($ttype==1)
											$ttype="Money Transfer Dispute";
											else if($ttype==2)
											$ttype="Technical Support";
											else if($ttype==3)
											$ttype="Sales Enquiry";
											else if($ttype==4)
											$ttype="Billing Enquiry";
											else if($ttype==5)
											$ttype="Commission Issues";
											$tdesc=$rs['ticket_description'];
											$tresp=$rs['ticket_response'];
											$tstatus=$rs['ticket_status'];
										}
									}
									if(isset($_POST['generate']))
									{
										$ttype=$_POST['ttype'];
										$ticket_desc=$_POST['ticket_desc'];
										$qry="insert into child_tickets value(NULL,'$ttype','$datetime_time','$user_id','$ticket_desc','$ticket_desc','1');";
										$res=mysql_query($qry);
										include_once('../functions/_zsms.php');
										zsms("9580958000","Ticket Generated by $user_id");
										if($res)
										{
											echo "<script>document.location.href='tickets.php'</script>";
										}
									}
									?>
							<form id="frmGenerateTicket" method="post">
								<div class="input-field col l8 m12 s12 offset-l2">
									<select name="ttype" required class="chosen">
										<option value="">Ticket Type</option>
										<option value="1">Money Transfer Dispute</option>
										<option value="2">Technical Support</option>
										<option value="3">Sales Enquiry</option>
										<option value="4">Billing Enquiry</option>
										<option value="5">Commission Issues</option>
									</select>
									<br><br>
								</div>

								<div class="input-field col l8 m12 s12 offset-l2">
									Ticket Description
									<input name="ticket_desc" required type="text" style="font-size: 1.8rem">
								</div>

								<div class="input-field col l8 m12 s12 offset-l2">
									<input value="Generate Ticket" class="waves-effect waves-light btn white-text green margin-bottom-10 ladda-button" name="generate" type="submit" />
								</div>
							</form>
                        </div>


                    </div>
                    
                </div>
            </div>
          </div>


            </div>
        </main>
    
        <?php include('_footer.php');?>
    </div>
    <script type="text/javascript" src="../js/jquery-2.1.1.min.js"></script>
			
			<script src="../js/spin.js"></script>
			<script src="../js/ladda.js"></script>
			<script src="../js/ladda.jquery.js"></script>
			

			<script type="text/javascript" src="../js/materialize.js"></script>
			<script type="text/javascript" src="../js/prism.min.js"></script>
			<script type="text/javascript" src="../js/mara.min.js"></script>
			<script src="../js/sweetalert2.min.js"></script>
			<script src="../js/site.js"></script>
			<script type="text/javascript" src="../js/chosen.jquery.min.js"></script>
			<script>
				$(".chosen").chosen();
			</script>

			<script>
				jQuery.fn.ForceNumericOnly =
			function () {
				return this.each(function () {
					$(this).keydown(function (e) {
						var key = e.charCode || e.keyCode || 0;
						// allow backspace, tab, delete, enter, arrows, numbers and keypad numbers ONLY
						// home, end, period, and numpad decimal
						return (
							key == 8 ||
							key == 9 ||
							key == 13 ||
							key == 46 ||
							key == 110 ||
							key == 190 ||
							(key >= 35 && key <= 40) ||
							(key >= 48 && key <= 57) ||
							(key >= 96 && key <= 105));
					});
				});
			};


				$(".numericOnlyText").ForceNumericOnly();



				function setactiveClass(id) {

					$(".myMenu li a").removeClass('active');

					$("#" + id).addClass('active');
					$("#" + id).parent().addClass('active');

				}
			</script>
    
    <script>
        setactiveClass("prodMar");
    </script>


    
</div>
</body>
</html>
