<?php

	$banks=array('1---UTIB---Axis Bank',
				'2---BARB---Bank of Baroda',
				'3---BKID---Bank of India',
				'4---CBIN---Central Bank of India',
				'5---CITI---Citibank',
				'6---HDFC---HDFC Bank',
				'7---ICIC---ICICI Bank',
				'8---IBKL---IDBI Bank',
				'9---IDIB---Indian Bank',
				'10---IOBA---Indian Overseas Bank',
				'11---PUNB---Punjab National Bank',
				'12---SBBJ---State Bank of Bikaner and Jaipur',
				'13---UBIN---Union Bank of India',
				'14---UCBA---UCO Bank',
				'16---YESB---Yes Bank',
				'17---BKDN---Dena Bank',
				'18---ABHY---Abhyudaya Co-Op Bank',
				'19---ADCB---Abu Dhabi Commercial Bank',
				'20---ALLA---Allahabad Bank',
				'21---ANDB---Andhra Bank',
				'22---BOFA---Bank of America',
				'23---BBKM---Bank of Bahrain and Kuwait',
				'24---BCEY---Bank of Ceylon',
				'25---MAHB---Bank of Maharashtra',
				'26---BOTM---Bank of Tokyo-Mitsubishi UFJ',
				'27---BARC---Barclays Bank',
				'28---BACB---Bassein Catholic Co-Op Bank',
				'29---BNPA---BNP Paribas',
				'30---CNRB---Canara Bank',
				'32---CSBK---Catholic Syrian Bank',
				'33---CTCB---Chinatrust Commercial Bank',
				'34---CCBL---Citizen Credit Co-Op Bank',
				'35---CIUB---City Union Bank',
				'37---CORP---Corporation Bank',
				'38---CRLY---Credit Agricole Corp N Investment Bank',
				'39---DBSS---DBS Bank',
				'41---DEUT---Deutsche Bank AG',
				'42---DCBL---Development Credit Bank',
				'43---DLXB---Dhanlaxmi Bank',
				'44---DICG---DICGC',
				'45---DNSB---Dombivli Nagari Sahakari Bank',
				'46---FIRN---Firstrand Bank',
				'47---HSBC---HSBC',
				'48---INDB---IndusInd Bank',
				'49---VYSA---ING Vysya Bank',
				'50---JSBL---Janakalyan Sahakari Bank',
				'51---JSBP---Janata Sahakari Bank,Pune',
				'52---CHAS---JP Morgan Chase Bank',
				'53---KCBL---Kapole Co-Op Bank',
				'54---KARB---Karnataka Bank',
				'55---KVBL---Karur Vysya Bank',
				'56---KKBK---Kotak Mahindra Bank',
				'57---MCBL---Mahanagar Co-Op Bank',
				'58---MSCI---Maharashtra State Co-Op Bank',
				'59---MSHQ---Mashreq Bank PSC',
				'60---MHCB---Mizuho Corporate Bank',
				'61---NICB---New India Co-Op Bank',
				'62---NKGS---NKGSB Co-Op Bank',
				'63---NNSB---Nutan Nagarik Sahakari Bank',
				'64---OIBA---Oman International Bank Saog',
				'65---ORBC---Oriental Bank of Commerce',
				'66---PJSB---Parsik Janata Sahakari Bank',
				'67---PMCB---Punjab and Maharashtra Co-Op Bank',
				'68---PSIB---Punjab and Sind Bank',
				'69---RNSB---Rajkot Nagarik Sahakari Bank',
				'70---RBIS---Reserve Bank of India',
				'71---SHBK---Shinhan Bank',
				'72---SOGE---Societe Generale',
				'73---SIBL---South Indian Bank',
				'74---SCBL---Standard Chartered Bank',
				'75---SBHY---State Bank of Hyderabad',
				'76---STCB---State Bank of Mauritius',
				'77---SBMY---State Bank of Mysore',
				'78---SBTR---State Bank of Travancore',
				'79---STBP---State Bank of Patiala',
				'80---SYNB---Syndicate Bank',
				'81---TMBL---Tamilnad Mercantile Bank',
				'82---NOSC---Bank of Nova Scotia',
				'83---AMCB---Ahmedabad Mercantile Co-Op Bank',
				'84---BCBM---Bharat Co-Op Bank, Mumbai',
				'85---COSB---Cosmos Co-Op Bank',
				'86---FDRL---The Federal Bank Ltd',
				'87---GBCB---Greater Bombay Co-Op Bank',
				'88---JAKA---Jammu and Kashmir Bank',
				'89---KCCB---Kalupur Commercial Co-Op Bank',
				'90---KSBC---Karnataka State Apex Co-Op',
				'91---KJSB---Kalyan Janata Sahakari Bank',
				'92---LAVB---Lakshmi Vilas Bank',
				'93---MSNU---Mehsana Urban Co-Op Bank',
				'94---NTBL---Nainital Bank',
				'95---RATN---Ratnakar Bank',
				'96---ABNA---Royal Bank of Scotland',
				'97---SRCB---Saraswat Co-Op Bank',
				'98---SVCB---The Shamrao Vithal Co-Operative Bank',
				'99---SPCB---Surat Peoples Co-Op Bank',
				'100---TJSB---Thane Janata Sahakari Bank',
				'101---TNSC---Tamilnadu State Apex Co-Op Bank',
				'102---WBSC---West Bengal State Co-Op Bank',
				'103---VIJB---Vijaya Bank',
				'108---SBIN---State Bank of India',
				'109---APMC---AP Mahesh Co-Op Urban Bank',
				'110---KUCB---Karad Urban Co-Op Bank',
				'111---KSCB---Karnataka State Co-Op Apex Bank, Bangalore',
				'112---NMCB---Nashik Merchants Co-Op Bank',
				'113---UBSW---UBS AG',
				'114---UTBI---United Bank of India',
				'115---KANG---Kangra Co-Op Bank',
				'116---KACE---Kangra Central Co-Op Bank',
				'117---PRTH---Prathama Bank',
				'119---ACGG---Chaitanya Godavari Grameena Bank',
				'120---ALLG---Allahabad UP Gramin Bank',
				'121---ANDG---Rushikulya Gramin Bank',
				'122---ASGB---Sharda Gramin Bank',
				'123---BARG---Nainital Almora Kshetriya Gramin Bank',
				'124---BARR---Baroda Rajasthan Kshetriya Gramin Bank',
				'125---BARU---Baroda Uttar Pradesh Gramin Bank',
				'126---BGGB---Baroda Gujarat Gramin Bank',
				'127---BJDG---Jhabua Dhar Kshetriya Gramin Bank',
				'128---BKDD---Dena Gujarat Gramin Bank',
				'129---BKDR---Durg Rajnandgaon Gramin Bank',
				'130---BKIB---Baitarani Gramin Bank',
				'131---BKIG---Aryavart Gramin Bank',
				'133---BWKG---Wainganga Krishna Gramin Bank',
				'134---CBBB---Uttar Bihar Gramin Bank',
				'135---CBIG---Ballia Etawah Gramin Bank',
				'136---CBIH---Hadoti Kshetriya Gramin Bank',
				'137---CKGB---Surguja Kshetriya Gramin Bank',
				'138---CMGB---South Malabar Gramin Bank',
				'139---CORG---Chickmangalur Kodagu Gramin Bank',
				'140---CPGB---Pragathi Gramin Bank',
				'141---CSGB---Shreyas Gramin Bank',
				'142---CSUG---Satpura Narmada Kshetriya Gramin Bank',
				'143---CUKG---Uttar Banga Kshetriya Gramin Bank',
				'144---CVAG---Vidharbha Kshetriya Gramin Bank',
				'145---FBIG---Madhya Bharat Gramin Bank',
				'146---GGBK---Gurgaon Gramin Bank',
				'147---HDFG---Malwa Gramin Bank',
				'148---ICIG---Mewar Anchalik Gramin Bank',
				'149---IDIG---Pallavan Grama Bank',
				'150---INGB---Neelachal Gramya Bank',
				'151---IOBG---Pandyan Gramin Bank',
				'152---IPBG---Puduvai Bharathiar Grama Bank',
				'153---JAKG---J&K Grameen Bank',
				'154---MAHG---Maharashtra Gramin Bank',
				'156---PRGB---Rajasthan Gramin Bank',
				'157---PSGB---Sarva UP Gramin Bank',
				'158---PSIG---Sutlej Gramin Bank',
				'159---PUHG---Himachal Gramin Bank',
				'160---PUNG---Madhya Bihar Gramin Bank',
				'161---PUNH---Sarva Haryana Gramin Bank',
				'162---SAPG---Andhra Pradesh Grameena Vikas Bank',
				'163---SBAP---Arunachal Pradesh Rural Bank',
				'164---SBBG---MG Baroda Gramin Bank',
				'165---SBHG---Telangana Grameena Bank',
				'166---SBIC---Chhattisgarh Gramin Bank',
				'167---SBIE---Ellaqui Dehati Bank',
				'168---SBIG---Mizoram Rural Bank',
				'169---SBIJ---Jharkhand Gramin Bank',
				'170---SBMG---Kaveri Grameena Bank',
				'171---SBOG---Vidisha Bhopal Kshetriya Gramin Bank',
				'172---SKRG---Krishna Gramin Bank',
				'173---SLDR---Langpi Dehangi Rural Bank',
				'174---SMEG---Meghalaya Rural Bank',
				'176---SPGB---Parvatiya Gramin Bank',
				'177---SRGB---Purvanchal Gramin Bank',
				'179---SSGB---Saurashtra Gramin Bank',
				'180---SSKG---Samastipur Kshetriya Gramin Bank',
				'181---SUTG---Uttarakhand Gramin Bank',
				'182---SUUG---Utkal Gramya Bank',
				'184---KVGB---Karnataka Vikas Grameena Bank',
				'185---APGB---Andhra Pragathi Grameena Bank',
				'186---SYNM---North Malabar Gramin Bank',
				'187---UASG---Assam Gramin Vikash Bank',
				'188---UBKG---Kashi Gomati Samyut Gramin Bank',
				'189---UCBG---Mahakaushal Kshetriya Gramin Bank',
				'190---UCBK---Bihar Kshetriya Gramin Bank',
				'191---UCKG---Kalinga Gramya Bank',
				'192---UJTG---Jaipur Thar Gramin Bank',
				'193---UPBG---Paschim Banga Gramin Bank',
				'194---URSG---Rewa-Sidhi Gramin Bank',
				'195---UTBB---Bangiya Gramin Bank',
				'196---UTBG---Manipur Rural ANK',
				'197---UTGB---Tripura Gramin Bank',
				'198---VIJG---Visveshwaraya Gramin Bank',
				'199---SBCG---Swarna Bharat Trust Cyber Grameen',
				'200---NMGB---NEFT Malwa Gramin Bank',
				'201---ABCC---ABN Amro Bank Credit Card',
				'202---BACC---Barclays Credit Card',
				'203---CICC---Citibank Credit Card',
				'204---HDCC---HDFC Bank Credit Card',
				'205---HSCC---HSBC Credit Card',
				'206---ICCC---ICICI Bank Credit Card',
				'207---KKCC---Kotak Mahindra Credit Card',
				'208---SBCC---State Bank of India Credit Card',
				'209---SCCC---Standard Chartered Credit Card',
				'210---UTCC---UTI Axis Bank Credit Card',
				'211---VICC---Vijaya Credit Card',
				'212---AMEX---American Express Credit Card',
				'213---JANA---Janaseva Sahakari Bank',
				'214---KAIJ---Kallapana Ichalkaranji Awade Janaseva Sahakari Bank',
				'215---ICIP---Pandharpur Merchant Co-Op Bank',
				'216---HDGB---Gayatri Bank',
				'217---HDFP---Pochampally Co-Op Urban Bank',
				'218---HDFA---Dr. Annasaheb Chougule Urban Co-Op Bank',
				'219---SDCB---Surat District Co-Op Bank',
				'220---HDFS---Suco Souharda Sahakari Bank',
				'221---IBKP---Pune Peoples Co-Op Bank',
				'222---ICSA---Shri Arihant Co-Op Bank',
				'223---KKBN---National Co-Op Bank',
				'224---HDPA---Parshwanath Co-Op Bank',
				'225---ASBL---Apna Sahakari Bank',
				'226---HDJC---Jalore Nagrik Sahakari Bank',
				'227---VARA---Varachha Co-Op Bank',
				'228---HDFJ---Janata Co-Op Bank, Malegaon',
				'229---ICIS---Shri Basaveshwar Sahakari Bank Niyamit Bagalkot',
				'230---KKBS---Shirpur Peoples Co-Op Bank',
				'231---BMBL---Bhartiya Mahila Bank',
				'232---KLGB---Kerala Gramin Bank',
				'233---PKGB---Pragathi Krishna Gramin Bank',
				'234---YESP---Yadagiri Lakshmi Narasimha Swamy Co-Op Urban Bank',
				'235---ICIH---Hutatma Sahakari Bank',
				'236---HPSC---Himachal Pradesh State Co-Op Bank',
				'237---ICIA---Adarsh Urban Co-Op Bank, Hyderabad',
				'238---ICIM---Mayani Urban Co-Op Bank',
				'239---ICPU---Pandharpur Urban Co-Op Bank',
				'240---SVAG---Vananchal Gramin Bank',
				'241---PPGB---Punjab Gramin Bank',
				'242---CVCB---Shree Veershaiv Co-Op Bank',
				'243---TDCB---Thrissur District Central Co-Op Bank',
				'244---VSBL---Vishweshwar Co-Op Bank',
				'245---HDRU---Raipur Urban Mercantile Co-Op Bank',
				'246---ICZS---Zila Sahkari Bank',
				'247---SBIT---Titwala',
				'248---SBDO---Dombivli East',
				'250---WBMG---MGCB Main',
				'251---HDSI---Sindhudurg District Central Co-Op Bank',
				'252---ICMA---Hamirpur District Co-Op Bank, Mahoba',
				'253---IBSM---Shivalik Mercantile Co-Op Bank',
				'254---HCBL---Hasti Co-Op Bank',
				'255---RSBL---Rajgurunagar Sahakari Bank',
				'256---BDBL---Bandhan Bank',
				'257---IBDU---Dapoli Urban Co-Op Bank',
				'258---GSCB---Gujarat State Co-Op Bank',
				'259---MUBL---Municipal Co-Op Bank',
				'260---ICRU---Rajapur Urban Co-Op Bank',
				'261---GSAD---Ahmedabad District Central Co-Op Bank',
				'262---IDFB---IDFC Bank',
				'263---SBRM---Rajasthan Marudhara Gramin Bank',
				'264---SUSB---Suvarnayug Sahakari Bank',
				'265---SUCO---Sutex Co-Op Bank',
				'266---NASB---Nagar Sahkari Bank',
				'267---IRTO---Irinjalakuda Town Co-Op Bank',
				'268---SHBH---Shivajirao Bhosale Sahakari Bank',
				'269---TBSB---Thane Bharat Sahakari Bank',
				'270---MCOB---Maratha Co-Op Bank',
				'271---IBJS---Pithoragarh Jila Sahkari Bank',
				'272---PCSB---Pune Cantonment Sahakari Bank',
				'273---UTTB---Uttarakhand Gramin Bank',
				'274---MASB---Malad Sahkari Bank',
				'275---SML---Shree Mahalaxmi Co-Op Bank',
				'276---MZSB---Moradabad Zila Sahkari Bank',
				'277---SCCB---Siwan Central Co-Op Bank',
				'278---MGBS---Madhyanchal Gramin Bank, Sagar',
				'279---TKGB---Triveni Kshetriya Gramin Bank',
				'280---RBCC---RBL Bank Credit Card',
				'281---PBCC---Punjab National Bank Credit Card',
				'283---IBCC---IndusInd Bank Credit Card',
				'284---CBCC---Canara Bank Credit Card',
				'285---IDCC---IDBI Bank Credit Card',
				'286---ANCC---Andhra Bank Credit Card',
				'287---BKCC---Bank Of India Credit Card',
				'288---BABC---Bank Of Baroda Credit Card',
				'289---IOGB---Odisha Gramya Bank',
				'290---UMSC---Udaipur Mahila Samrudhi Urban Co-Op Bank',
				'291---DSCB---Delhi State Co-Op Bank',
				'292---COBL---Citizen Co-Op Bank, Noida',
				'293---CUCB---Chikhli Urban Co-Op Bank',
				'294---PNSB---Poornawadi Nagrik Sahakari Bank',
				'295---AGBL---Ahmednagar Mer Co-Op Bank',
				'296---PSBL---Pavana Sahakari Bank',
				'297---UCBL---Urban Co-Op Bank',
				'298---AIRP---Airtel Payments Bank',
				'299---JPCB---Jalgaon Peoples Co-Op Bank',
				'300---VVSB---Vasai Vikas Co-op Bank',
				'301---ESFB---Equitas Small Finance Bank',
				'302---NCBL---Noble Co-Op Bank',
				'303---JDCB---Jalaun District Co-Op Bank',
				'304---VUCB---Vaidyanath Urban Co-Op Bank',
				'305---SGCB---Sapthagiri Grameena Bank',
				'306---AJHB---Ambarnath Jai Hind Co-Op Bank',
				'307---SVBL---Seva Vikas Co-Op Bank',
				'308---PPCB---Pachora Peoples Co-Op Bank',
				'309---IIPB---India Post Payments Bank',
				'310---BMCL---Bombay Mercantile Co-Op Bank',
				'311---MDCB---Malda District Central Co-Op Bank',
				'312---UJVN---Ujjivan Small Finance Bank',
				'313---JCBL---Jamia Co-Op Bank',
				'314---IUCB---Integral Urban Co-Op Bank',
				'315---ESMF---ESAF Small Finance Bank',
				'316---MGCB---Mogaveera Co-Op Bank',
				'317---AACB---Akhand Anand Co-Op Bank',
				'318---SBPP---Sardar Bhiladwala Pardi Peoples Co-Op Bank',
				'319---MPSS---Manvi Pattana Souharda Sahakari Bank',
				'320---SSSB---Shree Sharada Sahakari Bank',
				'321---ASML---Aircel Smart Money Ltd',
				'322---DCCL---Mumbai District Central Co-Operative Bank Ltd',
				'323---TCCB---The Thane District Central Co-Operative Bank Ltd',
				'324---ZCBL---The Zoroastrian Cooperative Bank Limited',
				'325---SSCB---The Saurashtra Cooperative Bank Ltd',
				'326---KNSB---Kurmanchal Nagar Sahkari Bank Ltd',
				'327---SURY---Suryoday Small Finance Bank',
				'328---AKJB---Akola Janata Commercial Co Operative Bank Ltd',
				'329---SAHE---The Sahebrao Deshmukh Co-operative Bank Ltd.',
				'330---CRUB---Shri Chhatrapati Rajarshi Shahu Urban Co-Op Bank Ltd',
				'331---ADCC---Akola District Central Co-operative Bank',
				'332---THCB---The Hindusthan Co-operative Bank Ltd.',
				'333---SSBL---Sadhana Sahakari Bank Ltd',
				'334---SDCC---The Sabarkantha District Central Cooperative Bank Ltd',
				'335---SSBM---Sharad Sahakari Bank Ltd. Manchar',
				'336---UUCB---Udaipur urban Co-operative bank Ltd',
				'337---VSCB---Vikas Souharda Co-operative Bank Limited');

$bank="";
include('../_gyan-info-login.php');
$j=0;
for($i=0;$i<count($banks);$i++)
{
	$bank="";
	
	$bank=explode("---",$banks[$i]);
	$qry="insert into eko_bank(eko_bank_id,bank_code,name,response,response_message,bank_name) value('".$bank[0]."','".$bank[1]."','".$bank[2]."','','','');";
	$j+=mysql_query($qry);
}
echo "$j banks inserted";


?>